# language: php
filter:
    excluded_paths:
        - tests/
        - build/
        - vendor/

coding_style:
    php:
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

checks:
    php:
        code_rating: true
        duplication: true
        uppercase_constants: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_goto: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        parameter_doc_comments: true
        use_self_instead_of_fqcn: true
        simplify_boolean_return: true
        avoid_fixme_comments: true
        return_doc_comments: true

tools:
    php_code_sniffer:
        enabled: true
        config:
            include_standards:
                - phpcs.xml
    php_cpd:
        enabled: true
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml
    php_loc:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_code_coverage:
        enabled: true
    sensiolabs_security_checker:
        enabled: true

build:
    tests:
        override:
            -
                command: 'phpunit -c phpunit.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
